name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate a snake game from the user's contributions graph
        uses: Platane/snk@v3
        with:
          github_user_name: jcarloscarmo
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          # Adicione esta linha para que o arquivo seja salvo na branch 'main'
          target_branch: main
