name: Generate Data

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions:
      contents: write  # <<<<<<<< Adicione este bloco aqui
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jcarloscarmo
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction
